In [1]:
import numpy as np

a = np.zeros(3)
a

array([0., 0., 0.])

In [2]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
z.shape

(10,)

In [4]:
z.shape = (10, 1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [7]:
z = np.linspace(2, 10, 5)     # From 2 to 10 with 5 elements
z

array([ 2.,  4.,  6.,  8., 10.])

In [8]:
z = np.array([10, 20])
z

array([10, 20])

In [9]:
a_list = [1, 2, 3, 4, 5]
z = np.array(a_list)
z

array([1, 2, 3, 4, 5])

In [10]:
b_list = [[9, 5, 3], [3, 5, 9]]
z = np.array(b_list)
z

array([[9, 5, 3],
       [3, 5, 9]])

In [11]:
z.shape

(2, 3)

In [12]:
?z

Type:            ndarray
String form:    
[[9 5 3]
 [3 5 9]]
Length:          2
File:            c:\users\user\appdata\local\programs\python\python36\lib\site-packages\numpy\__init__.py
Docstring:       <no docstring>
Class docstring:
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : 

In [13]:
np.random.seed(0)
zl = np.random.randint(10, size=6)
zl

array([5, 0, 3, 3, 7, 9])

In [15]:
np.sort(zl)
zl

array([5, 0, 3, 3, 7, 9])